site_name: Plantilla para Documentación
site_description: Documentación de ingeniería y producción de hardware.

theme:
  name: material
  language: es
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    # Modo claro (Estilo de la imagen: barra superior blanca y limpia, detalles azules)
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Modo oscuro (Mantiene el azul moderno pero descansa la vista con fondo oscuro)
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    # Modo claro
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Modo oscuro
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

  features:
    - navigation.tabs          # Pestañas horizontales superiores
    - navigation.sections      # Secciones agrupadas en el menú lateral
    - navigation.expand        # Menús desplegados por defecto
    - navigation.top           # Botón flotante para regresar arriba
    - navigation.instant       # Carga páginas al instante sin recarga completa
    - content.code.copy        # Botón de copiar código
    - content.tooltips         # Tooltips informativos
    - toc.follow               # El índice sigue el scroll

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
